name:               luna-manager
version:            "0.1"
author:             New Byte Order <contact@newbyteorder.com>
maintainer:         New Byte Order <contact@newbyteorder.com>

dependencies:
  - prologue
  - ansi-terminal
  - ascii-progress
  - base64-bytestring
  - io-streams
  - path
  - network
  - conduit
  - base
  - directory
  - exceptions
  - aeson
  - yaml
  - text
  - typed-process
  - http-conduit
  - http-types
  - filepath
  - network-uri
  - bytestring
  - optparse-applicative
  - split
  - lens
  - dependent-state
  - containers
  - resourcet
  - optparse-applicative
  - typelevel
  - signal
  - monad-control

  - lens-utils
  - constraints
  - transformers
  - mtl
  - shelly
  - conduit-extra
  - system-filepath
  - safe-exceptions
  - errors
  - aeson-pretty
  - time
  - uuid


default-extensions:
    - AllowAmbiguousTypes
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveGeneric
    - DuplicateRecordFields
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - NoImplicitPrelude
    - OverloadedStrings
    - RankNTypes
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeOperators


executables:
  luna-manager:
    main:          Main.hs
    source-dirs:   src
    ghc-options: -threaded
