http_port: 80
max_clients: 200
home: '{{ ansible_env.HOME }}'
luna_repo_path: 'ssh://git@github.com/luna/luna-manager'
luna_dir: '{{ home }}/luna-develop'
luna_tools_dir: '{{ luna_dir }}/tools'
luna_apps_dir: '{{ luna_dir }}/apps'
luna_libs_dir: '{{ luna_dir }}/libs'
luna_manager_dir: '{{ luna_apps_dir }}/luna-manager'
luna_studio_dir: '{{ luna_apps_dir }}/luna-studio'
luna_manager_url: 'http://packages.luna-lang.org/linux/manager/luna-manager'
luna_manager_bin: '{{ luna_manager_dir }}/executables/luna-manager'
source_env: 'source {{ luna_studio_dir }}/luna-shell.sh'
pyenv_root: '{{ luna_tools_dir }}/python/pyenv'
pyenv_bin: '{{ pyenv_root }}/bin/pyenv'
