---
- hosts: all
  any_errors_fatal: true
  remote_user: vagrant
  become_user: root
  vars_files:
    - common-vars.yml
  environment:
    LD_LIBRARY_PATH: '{{ luna_libs_dir }}:{{ ansible_env.LD_LIBRARY_PATH | default("") }}'
    PYENV_ROOT: '{{ pyenv_root }}'

  tasks:
  - name: fetch the new repo
    shell: 'git checkout master && git pull origin master'
    args:
      executable: /bin/bash
      chdir: '{{ luna_studio_dir }}'

  - name: create the next luna studio version
    shell: '{{ source_env }} && {{ luna_manager_bin}} next-version {{ luna_studio_dir }}/luna-package.yaml'
    args:
      executable: /bin/bash
      chdir: '{{ luna_manager_dir }}'

  - name: build luna package
    shell: '{{ source_env }} && {{ luna_manager_bin }} make-package {{ luna_studio_dir }}/luna-package.yaml --build-from-head'
    args:
      executable: /bin/bash
      chdir: '{{ luna_manager_dir }}'

  - name: upload luna package to S3
    shell: '{{ source_env }} && python deploy/build_package -p {{ luna_studio_dir }} --deploy-only'
    args:
      executable: /bin/bash
      chdir: '{{ luna_manager_dir }}'
